const HOTELS = [
  { name: 'برج العرب', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/burj/400/300', description: 'أشهر فندق في العالم بتصميم الشراع الفاخر وإطلالات على الخليج.' },
  { name: 'أتلانتس النخلة', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/atlantis/400/300', description: 'منتجع أسطوري على جزيرة النخلة مع أكواريوم ضخم وشاطئ خاص.' },
  { name: 'جميرا بيتش', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/jumeirah/400/300', description: 'منتجع فاخر على الشاطئ بمرافق مائية ومطاعم عالمية.' },
  { name: 'رافلز دبي', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/rafflesdxb/400/300', description: 'فخامة استثنائية مع خدمة بوتل خاصة ومطاعم حائزة على نجوم.' },
  { name: 'أرماني هوتيل', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/armani/400/300', description: 'تصميم راقٍ من جورجيو أرماني داخل برج خليفة.' },
  { name: 'فورسيزونز دبي', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/fsdxb/400/300', description: 'إقامة راقية على الواجهة البحرية بأجواء هادئة.' },
  { name: 'ميلينيوم داون تاون', city: 'دبي', country: 'الإمارات', image: 'https://picsum.photos/seed/milldxb/400/300', description: 'فندق عصري قريب من نافورة دبي ومركز دبي مول.' },
  { name: 'قصر الإمارات', city: 'أبوظبي', country: 'الإمارات', image: 'https://picsum.photos/seed/emirates/400/300', description: 'قصر فندقي فاخر بشواطئ خاصة ومرافق ملكية.' },
  { name: 'سانت ريجيس أبوظبي', city: 'أبوظبي', country: 'الإمارات', image: 'https://picsum.photos/seed/regis/400/300', description: 'فندق راقٍ على جزيرة السعديات بإطلالات على البحر.' },
  { name: 'سيراغان بالاس', city: 'إسطنبول', country: 'تركيا', image: 'https://picsum.photos/seed/ciragan/400/300', description: 'قصر عثماني تاريخي تحول إلى فندق فاخر على البوسفور.' },
  { name: 'شيراتون إسطنبول', city: 'إسطنبول', country: 'تركيا', image: 'https://picsum.photos/seed/sheristan/400/300', description: 'فندق عصري يطل على مضيق البوسفور بمرافق متكاملة.' },
  { name: 'آيا صوفيا مانشنز', city: 'إسطنبول', country: 'تركيا', image: 'https://picsum.photos/seed/ayasofya/400/300', description: 'إقامة فاخرة في قلب المدينة القديمة قرب المسجد الأزرق.' },
  { name: 'السويسري غراند', city: 'إسطنبول', country: 'تركيا', image: 'https://picsum.photos/seed/swissistan/400/300', description: 'فندق كبير بخدمات خمس نجوم ومسبح داخلي.' },
  { name: 'رافلز إسطنبول', city: 'إسطنبول', country: 'تركيا', image: 'https://picsum.photos/seed/raffistan/400/300', description: 'فخامة حديثة في منطقة زورلو سنتر التجارية.' },
  { name: 'أندريا أنطاليا', city: 'أنطاليا', country: 'تركيا', image: 'https://picsum.photos/seed/andrea/400/300', description: 'منتجع شامل على شواطئ البحر المتوسط التركية.' },
  { name: 'ريمي أنطاليا', city: 'أنطاليا', country: 'تركيا', image: 'https://picsum.photos/seed/remi/400/300', description: 'منتجع عائلي جميل بإطلالات على المدينة القديمة.' },
  { name: 'ماريوت القاهرة', city: 'القاهرة', country: 'مصر', image: 'https://picsum.photos/seed/marriottcai/400/300', description: 'فندق مميز في مدينة نصر بغرف واسعة ومطاعم متنوعة.' },
  { name: 'مينا هاوس', city: 'الجيزة', country: 'مصر', image: 'https://picsum.photos/seed/menahouse/400/300', description: 'فندق تاريخي يطل مباشرة على أهرامات الجيزة.' },
  { name: 'فورسيزونز النيل', city: 'القاهرة', country: 'مصر', image: 'https://picsum.photos/seed/fsnile/400/300', description: 'فندق فاخر على ضفاف النيل بخدمات عالمية.' },
  { name: 'ستيجنبرغر النيل', city: 'القاهرة', country: 'مصر', image: 'https://picsum.photos/seed/steinile/400/300', description: 'فندق أنيق بموقع مركزي قرب وسط القاهرة.' },
  { name: 'الكونراد الغردقة', city: 'الغردقة', country: 'مصر', image: 'https://picsum.photos/seed/conradhur/400/300', description: 'منتجع على البحر الأحمر بشاطئ خاص ورياضات مائية.' },
  { name: 'أوبروي الغردقة', city: 'الغردقة', country: 'مصر', image: 'https://picsum.photos/seed/oberoi/400/300', description: 'منتجع هادئ بشاليهات خاصة وإطلالة على الجزر.' },
  { name: 'سوميت شرم الشيخ', city: 'شرم الشيخ', country: 'مصر', image: 'https://picsum.photos/seed/summitsh/400/300', description: 'منتجع على شاطئ خليج نعمة بأجواء استوائية.' },
  { name: 'فورسيزونز شرم', city: 'شرم الشيخ', country: 'مصر', image: 'https://picsum.photos/seed/fssh/400/300', description: 'منتجع فاخر بإطلالات على البحر الأحمر والغوص الممتاز.' },
  { name: 'ماريوت الأسكندرية', city: 'الإسكندرية', country: 'مصر', image: 'https://picsum.photos/seed/marriottalx/400/300', description: 'قصر تحول إلى فندق يطل على البحر المتوسط مباشرة.' },
  { name: 'فندق ريتم الإسكندرية', city: 'الإسكندرية', country: 'مصر', image: 'https://picsum.photos/seed/ritalex/400/300', description: 'فندق عصري على الواجهة البحرية بموقع مميز.' },
  { name: 'رياض العرائش مراكش', city: 'مراكش', country: 'المغرب', image: 'https://picsum.photos/seed/riyadmar/400/300', description: 'رياض مغربي تقليدي مفروش بأناقة وسط المدينة العتيقة.' },
  { name: 'مامونيا مراكش', city: 'مراكش', country: 'المغرب', image: 'https://picsum.photos/seed/mamounia/400/300', description: 'من أشهر فنادق العالم بحدائق ساحرة وخدمة ملكية.' },
  { name: 'سوفيتيل مراكش', city: 'مراكش', country: 'المغرب', image: 'https://picsum.photos/seed/sofitelmar/400/300', description: 'منتجع فاخر بمسابح واسعة وأجواء مغربية راقية.' },
  { name: 'حياة ريجنسي الدار البيضاء', city: 'الدار البيضاء', country: 'المغرب', image: 'https://picsum.photos/seed/hyattcasa/400/300', description: 'فندق عصري يطل على المحيط الأطلسي.' },
  { name: 'فور سيزونز الرياض', city: 'الرياض', country: 'السعودية', image: 'https://picsum.photos/seed/fsriyadh/400/300', description: 'فندق فاخر في برج المملكة بأعلى مستويات الخدمة.' },
  { name: 'ريتز كارلتون الرياض', city: 'الرياض', country: 'السعودية', image: 'https://picsum.photos/seed/ritzryd/400/300', description: 'مجمع فندقي فخم بحدائق ومرافق متكاملة.' },
  { name: 'رافلز جدة', city: 'جدة', country: 'السعودية', image: 'https://picsum.photos/seed/raffjeddah/400/300', description: 'فندق أنيق على الكورنيش بإطلالات على البحر الأحمر.' },
  { name: 'هيلتون جدة', city: 'جدة', country: 'السعودية', image: 'https://picsum.photos/seed/hiltjeddah/400/300', description: 'فندق مركزي قريب من المطار والمولات.' },
  { name: 'فندق فيرمونت مكة', city: 'مكة', country: 'السعودية', image: 'https://picsum.photos/seed/fairmakkah/400/300', description: 'إقامة قريبة من الحرم المكي بإطلالات مميزة.' },
  { name: 'أبراج الساعة مكة', city: 'مكة', country: 'السعودية', image: 'https://picsum.photos/seed/clocktower/400/300', description: 'فندق ضخم داخل أبراج الساعة المطلة على الحرم مباشرة.' },
  { name: 'أوبيروي المدينة', city: 'المدينة', country: 'السعودية', image: 'https://picsum.photos/seed/obermed/400/300', description: 'فندق فاخر قريب من المسجد النبوي الشريف.' },
  { name: 'الفصول الأربعة الدوحة', city: 'الدوحة', country: 'قطر', image: 'https://picsum.photos/seed/fsdoha/400/300', description: 'منتجع فاخر على جزيرة خاصة قبالة الدوحة.' },
  { name: 'شيراتون الدوحة', city: 'الدوحة', country: 'قطر', image: 'https://picsum.photos/seed/sherdoha/400/300', description: 'معلم فندقي على الكورنيش بمرافق واسعة.' },
  { name: 'بانيان تري الدوحة', city: 'الدوحة', country: 'قطر', image: 'https://picsum.photos/seed/banyandoha/400/300', description: 'فندق راقٍ في قلب منطقة مشيرب التاريخية.' },
  { name: 'ريتز كارلتون البحرين', city: 'المنامة', country: 'البحرين', image: 'https://picsum.photos/seed/ritzbah/400/300', description: 'منتجع فاخر بشاطئ خاص على خليج البحرين.' },
  { name: 'إنتركونتيننتال المنامة', city: 'المنامة', country: 'البحرين', image: 'https://picsum.photos/seed/icbah/400/300', description: 'فندق مركزي بإطلالات على العاصمة.' },
  { name: 'الريتز الكويت', city: 'مدينة الكويت', country: 'الكويت', image: 'https://picsum.photos/seed/ritzkw/400/300', description: 'فندق فاخر على الواجهة البحرية للكويت.' },
  { name: 'جراند حياة الكويت', city: 'مدينة الكويت', country: 'الكويت', image: 'https://picsum.photos/seed/ghkw/400/300', description: 'فندق أنيق قريب من الأبراج والمولات.' },
  { name: 'السدرة مسقط', city: 'مسقط', country: 'عُمان', image: 'https://picsum.photos/seed/albus/400/300', description: 'فندق عصري بعمارة عمانية مميزة.' },
  { name: 'كيمبينسكي مسقط', city: 'مسقط', country: 'عُمان', image: 'https://picsum.photos/seed/kempmuscat/400/300', description: 'منتجع على الشاطئ بأجواء هادئة وفخمة.' },
  { name: 'الفورسيزونز عمان', city: 'عمّان', country: 'الأردن', image: 'https://picsum.photos/seed/fsamman/400/300', description: 'فندق راقٍ على تلال عمّان بإطلالات ساحرة.' },
  { name: 'القدس الذهبية', city: 'عمّان', country: 'الأردن', image: 'https://picsum.photos/seed/goldamman/400/300', description: 'فندق مريح بموقع مركزي في جبل عمان.' },
  { name: 'الموفنبيك العقبة', city: 'العقبة', country: 'الأردن', image: 'https://picsum.photos/seed/movenaqaba/400/300', description: 'منتجع على شاطئ البحر الأحمر بمسبح خارجي.' },
  { name: 'الفينيسيا بيروت', city: 'بيروت', country: 'لبنان', image: 'https://picsum.photos/seed/venbeirut/400/300', description: 'منتجع راقٍ على الواجهة البحرية لبيروت.' },
  { name: 'الفينيسيا جونيه', city: 'جونيه', country: 'لبنان', image: 'https://picsum.photos/seed/venjounieh/400/300', description: 'منتجع جبلي-بحرى بإطلالات على خليج جونيه.' },
  { name: 'الدانيا تونس', city: 'تونس', country: 'تونس', image: 'https://picsum.photos/seed/daniatun/400/300', description: 'فندق بحري أنيق في ضواحي العاصمة التونسية.' },
  { name: 'الكرابلاس سوسة', city: 'سوسة', country: 'تونس', image: 'https://picsum.photos/seed/karablas/400/300', description: 'منتجع على الشاطئ في قلب المدينة السياحية.' },
  { name: 'الفندق الفلسطيني القدس', city: 'القدس', country: 'فلسطين', image: 'https://picsum.photos/seed/palhotel/400/300', description: 'فندق هادئ قريب من البلدة القديمة.' },
  { name: 'جراند بارك بغداد', city: 'بغداد', country: 'العراق', image: 'https://picsum.photos/seed/grandbg/400/300', description: 'فندق عصري في قلب بغداد بمرافق متكاملة.' },
  { name: 'الأشجار الدولية أربيل', city: 'أربيل', country: 'العراق', image: 'https://picsum.photos/seed/erbil/400/300', description: 'فندق راقٍ قريب من قلعة أربيل التاريخية.' },
  { name: 'فندق الشيراتون بغداد', city: 'بغداد', country: 'العراق', image: 'https://picsum.photos/seed/sherbg/400/300', description: 'فندق خمس نجوم بموقع استراتيجي وخدمة مميزة.' },
  { name: 'ريتز باريس', city: 'باريس', country: 'فرنسا', image: 'https://picsum.photos/seed/ritzparis/400/300', description: 'فندق أسطوري يجمع الفخامة والتاريخ في قلب باريس.' },
  { name: 'فورسيزونز باريس', city: 'باريس', country: 'فرنسا', image: 'https://picsum.photos/seed/fsparis/400/300', description: 'فندق فاخر قريب من قوس النصر بلمسة فرنسية.' },
  { name: 'سوفيتيل باريس', city: 'باريس', country: 'فرنسا', image: 'https://picsum.photos/seed/sofitpar/400/300', description: 'فندق عصري بإطلالات على برج إيفل.' },
  { name: 'ذا سافي لندن', city: 'لندن', country: 'بريطانيا', image: 'https://picsum.photos/seed/savoy/400/300', description: 'فندق تاريخي فاخر على ضفاف نهر التايمز.' },
  { name: 'ذا ريتز لندن', city: 'لندن', country: 'بريطانيا', image: 'https://picsum.photos/seed/ritzlondon/400/300', description: 'رمز للفخامة الباريسية-الإنجليزية في ميدان بيكاديلي.' },
  { name: 'شيراتون لندن', city: 'لندن', country: 'بريطانيا', image: 'https://picsum.photos/seed/sherlondon/400/300', description: 'فندق عصري قريب من ويستفيلد والمولات.' },
  { name: 'أدلون برلين', city: 'برلين', country: 'ألمانيا', image: 'https://picsum.photos/seed/adlon/400/300', description: 'فندق تاريخي فاخر قبالة بوابة براندنبورغ.' },
  { name: 'رافلز برلين', city: 'برلين', country: 'ألمانيا', image: 'https://picsum.photos/seed/raffberlin/400/300', description: 'فندق أنيق في قلب العاصمة الألمانية.' },
  { name: 'ميونيخ ماربل', city: 'ميونخ', country: 'ألمانيا', image: 'https://picsum.photos/seed/bayris/400/300', description: 'فندق بايريشر هوف الأسطوري قرب ساحة مارين.' },
  { name: 'سافوي فلورنسا', city: 'فلورنسا', country: 'إيطاليا', image: 'https://picsum.photos/seed/savoyflor/400/300', description: 'فندق كلاسيكي أنيق في قلب فلورنسا الفنية.' },
  { name: 'الدنيل روما', city: 'روما', country: 'إيطاليا', image: 'https://picsum.photos/seed/danieli/400/300', description: 'فندق ساحر بإطلالة على السلالم الإسبانية.' },
  { name: 'ميلانو أركو', city: 'ميلانو', country: 'إيطاليا', image: 'https://picsum.photos/seed/arco/400/300', description: 'فندق عصري قريب من الكاتدرائية الشهيرة.' },
  { name: 'بريستول روما', city: 'روما', country: 'إيطاليا', image: 'https://picsum.photos/seed/bristol/400/300', description: 'فندق تاريخي فاخر قريب من نافورة تريفي.' },
  { name: 'فينيسيا باول', city: 'البندقية', country: 'إيطاليا', image: 'https://picsum.photos/seed/venpau/400/300', description: 'فندق رومانسي على القناة الكبرى في البندقية.' },
  { name: 'ريتز برشلونة', city: 'برشلونة', country: 'إسبانيا', image: 'https://picsum.photos/seed/ritzbar/400/300', description: 'فندق فاخر بإطلالات على شارع باسيو دي غراسيا.' },
  { name: 'الويست برشلونة', city: 'برشلونة', country: 'إسبانيا', image: 'https://picsum.photos/seed/wbar/400/300', description: 'فندق حديث قريب من الشاطئ بمناظر بانورامية.' },
  { name: 'بالاس مدريد', city: 'مدريد', country: 'إسبانيا', image: 'https://picsum.photos/seed/palacio/400/300', description: 'فندق تاريخي فاخر قرب القصر الملكي.' },
  { name: 'ماربيلا غران', city: 'ماربيا', country: 'إسبانيا', image: 'https://picsum.photos/seed/marbella/400/300', description: 'منتجع فاخر على كوستا ديل سول.' },
  { name: 'الريتز كارلتون لشبونة', city: 'لشبونة', country: 'البرتغال', image: 'https://picsum.photos/seed/ritzlisbon/400/300', description: 'فندق أنيق بإطلالات على نهر تاجة.' },
  { name: 'سويسيوتيل جنيف', city: 'جنيف', country: 'سويسرا', image: 'https://picsum.photos/seed/ssgva/400/300', description: 'فندق راقٍ قريب من بحيرة جنيف.' },
  { name: 'بورين فيينا', city: 'فيينا', country: 'النمسا', image: 'https://picsum.photos/seed/bristolvie/400/300', description: 'فندق تاريخي فاخر قرب الأوبرا.' },
  { name: 'الامستردام سافوي', city: 'أمستردام', country: 'هولندا', image: 'https://picsum.photos/seed/savoyams/400/300', description: 'فندق مريح على القنوات الهولندية.' },
  { name: 'أنتلانيك أثينا', city: 'أثينا', country: 'اليونان', image: 'https://picsum.photos/seed/athenian/400/300', description: 'فندق عصري بإطلالات على الأكروبوليس.' },
  { name: 'سانتوريني بلو', city: 'سانتوريني', country: 'اليونان', image: 'https://picsum.photos/seed/santblue/400/300', description: 'منتجع بمسابح لا متناهية على كالديرا سانتوريني.' },
  { name: 'ميكونوس جريس', city: 'ميكونوس', country: 'اليونان', image: 'https://picsum.photos/seed/gracemyk/400/300', description: 'منتجع راقٍ على شاطئ ميكونوس.' },
  { name: 'البلازا نيويورك', city: 'نيويورك', country: 'أمريكا', image: 'https://picsum.photos/seed/plaza/400/300', description: 'فندق أيقوني قبالة سنترال بارك.' },
  { name: 'ريتز نيويورك', city: 'نيويورك', country: 'أمريكا', image: 'https://picsum.photos/seed/ritznyc/400/300', description: 'فندق فاخر في قلب مانهاتن.' },
  { name: 'وولفدورف أستوريا', city: 'نيويورك', country: 'أمريكا', image: 'https://picsum.photos/seed/waldorf/400/300', description: 'رمز الفخامة الأمريكية بأسطورة تاريخية.' },
  { name: 'فورسيزونز ميامي', city: 'ميامي', country: 'أمريكا', image: 'https://picsum.photos/seed/fsmia/400/300', description: 'منتجع على الشاطئ بطراز آرت ديكو مميز.' },
  { name: 'ذا فاونتنبلو', city: 'ميامي', country: 'أمريكا', image: 'https://picsum.photos/seed/fountainbl/400/300', description: 'منتجع أسطوري على شاطئ ميامي.' },
  { name: 'بيلماجيو لاس فيغاس', city: 'لاس فيغاس', country: 'أمريكا', image: 'https://picsum.photos/seed/bellagio/400/300', description: 'فندق شهير بنافورته الراقصة على الطراز الإيطالي.' },
  { name: 'سيزارز لاس فيغاس', city: 'لاس فيغاس', country: 'أمريكا', image: 'https://picsum.photos/seed/caesars/400/300', description: 'فندق ضخم على طراز الإمبراطورية الرومانية.' },
  { name: 'شيكاغو ترمبل', city: 'شيكاغو', country: 'أمريكا', image: 'https://picsum.photos/seed/trumpchi/400/300', description: 'فندق فاخر بإطلالات على بحيرة ميشيغان.' },
  { name: 'ديزني وورلد أورلاندو', city: 'أورلاندو', country: 'أمريكا', image: 'https://picsum.photos/seed/disneyor/400/300', description: 'تجربة سحرية للعائلات داخل عالم ديزني.' },
  { name: 'بيفرلي هيلز', city: 'لوس أنجلوس', country: 'أمريكا', image: 'https://picsum.photos/seed/beverly/400/300', description: 'فندق فاخر في قلب هوليوود.' },
  { name: 'فورسيزونز تورنتو', city: 'تورونتو', country: 'كندا', image: 'https://picsum.photos/seed/fstor/400/300', description: 'فندق أنيق في أطول برج سكني بكندا.' },
  { name: 'ريديسون فانكوفر', city: 'فانكوفر', country: 'كندا', image: 'https://picsum.photos/seed/radvanc/400/300', description: 'فندق مريح قريب من وسط فانكوفر.' },
  { name: 'ريتز كارلتون كانكون', city: 'كانكون', country: 'المكسيك', image: 'https://picsum.photos/seed/ritzcancun/400/300', description: 'منتجع فاخر على شواطئ الكاريبي.' },
  { name: 'كوباكابانا ريو', city: 'ريو دي جانيرو', country: 'البرازيل', image: 'https://picsum.photos/seed/copacabana/400/300', description: 'فندق أيقوني على شاطئ كوباكابانا الشهير.' },
  { name: 'فاسانو ساو باولو', city: 'ساو باولو', country: 'البرازيل', image: 'https://picsum.photos/seed/fasanosp/400/300', description: 'فندق راقٍ في حي جاردينز الفاخر.' },
  { name: 'بوركوريو باينوس', city: 'بوينس آيرس', country: 'الأرجنتين', image: 'https://picsum.photos/seed/parkbsas/400/300', description: 'فندق فاخر بأسلوب أوروبي في العاصمة الأرجنتينية.' },
  { name: 'سيام بانكوك', city: 'بانكوك', country: 'تايلاند', image: 'https://picsum.photos/seed/siam/400/300', description: 'منتجع فاخر وسط الطبيعة بمسابح لا متناهية.' },
  { name: 'ماندارين بانكوك', city: 'بانكوك', country: 'تايلاند', image: 'https://picsum.photos/seed/mandarinbkk/400/300', description: 'فندق أسطوري على ضفاف نهر تشاو فرايا.' },
  { name: 'أمانبوري فوكيت', city: 'فوكيت', country: 'تايلاند', image: 'https://picsum.photos/seed/amanpuri/400/300', description: 'منتجع فاخر على تلال بانسا ويطل على خليج أندامان.' },
  { name: 'أمانجاني فوكيت', city: 'فوكيت', country: 'تايلاند', image: 'https://picsum.photos/seed/amanyara/400/300', description: 'منتجع هادئ بإطلالات استوائية خلابة.' },
  { name: 'ماندارين كوالالمبور', city: 'كوالالمبور', country: 'ماليزيا', image: 'https://picsum.photos/seed/mandarinkl/400/300', description: 'فندق فاخر قرب برجي بتروناس.' },
  { name: 'الرانتاو لانكاوي', city: 'لانكاوي', country: 'ماليزيا', image: 'https://picsum.photos/seed/rantau/400/300', description: 'منتجع على شاطئ جزيرة لانكاوي.' },
  { name: 'مارينا باي ساندز', city: 'سنغافورة', country: 'سنغافورة', image: 'https://picsum.photos/seed/mbs/400/300', description: 'فندق أيقوني بمسبحه الشهير فوق البحر.' },
  { name: 'رافلز سنغافورة', city: 'سنغافورة', country: 'سنغافورة', image: 'https://picsum.photos/seed/rafflessg/400/300', description: 'فندق تاريخي أسطوري بعمارة استعمارية أنيقة.' },
  { name: 'أمان بالي', city: 'باليم', country: 'إندونيسيا', image: 'https://picsum.photos/seed/amanbali/400/300', description: 'منتجع راقٍ وسط حقول الأرز في أوبود.' },
  { name: 'أمانجاي بالي', city: 'أوبود', country: 'إندونيسيا', image: 'https://picsum.photos/seed/amangiri/400/300', description: 'منتجع فاخر بإطلالات على نهر أيونغ.' },
  { name: 'هانوي لوتيه', city: 'هانوي', country: 'فيتنام', image: 'https://picsum.photos/seed/metropole/400/300', description: 'فندق تاريخي فاخر في قلب هانوي.' },
  { name: 'تاج محل مومباي', city: 'مومباي', country: 'الهند', image: 'https://picsum.photos/seed/tajmum/400/300', description: 'فندق أسطوري أيقوني في مومباي.' },
  { name: 'أوبروي نيودلهي', city: 'نيودلهي', country: 'الهند', image: 'https://picsum.photos/seed/oberoi/400/300', description: 'فندق فاخر بحدائق ساحرة في العاصمة الهندية.' },
  { name: 'بانغالور ويستين', city: 'بنغالور', country: 'الهند', image: 'https://picsum.photos/seed/westbg/400/300', description: 'فندق عصري لرجال الأعمال في مدينة التقنية.' },
  { name: 'بيرج شانغهاي', city: 'شانغهاي', country: 'الصين', image: 'https://picsum.photos/seed/bundsh/400/300', description: 'فندق فاخر بإطلالات على بوند شانغهاي.' },
  { name: 'الوايت بيجين', city: 'بكين', country: 'الصين', image: 'https://picsum.photos/seed/wjbj/400/300', description: 'فندق راقٍ قريب من المدينة المحرمة.' },
  { name: 'بارك حياة طوكيو', city: 'طوكيو', country: 'اليابان', image: 'https://picsum.photos/seed/phytkyo/400/300', description: 'فندق فاخر بإطلالات على حديقة شينجوكو.' },
  { name: 'ريتز كارلتون كيوتو', city: 'كيوتو', country: 'اليابان', image: 'https://picsum.photos/seed/ritzkyo/400/300', description: 'فندق ياباني تقليدي فاخر بأجواء الزن.' },
  { name: 'فورسيزونز سيول', city: 'سيول', country: 'كوريا', image: 'https://picsum.photos/seed/fsseoul/400/300', description: 'فندق فاخر في منطقة جانغنام.' },
  { name: 'شيلا سيول', city: 'سيول', country: 'كوريا', image: 'https://picsum.photos/seed/shilla/400/300', description: 'فندق أيقوني بإطلالات على قلعة نامسان.' },
  { name: 'جونغهام المالديف', city: 'ماليه', country: 'المالديف', image: 'https://picsum.photos/seed/joali/400/300', description: 'منتجع فاخر على الماء بفيلات خاصة.' },
  { name: 'المالديف ريجنت', city: 'ماليه', country: 'المالديف', image: 'https://picsum.photos/seed/regentmd/400/300', description: 'منتجع على جزيرة خاصة بشواطئ بكر.' },
  { name: 'كنزارا سريلانكا', city: 'كولومبو', country: 'سريلانكا', image: 'https://picsum.photos/seed/kingsri/400/300', description: 'منتجع فاخر بإطلالات على المحيط الهندي.' },
  { name: 'سيدني أوبرا', city: 'سيدني', country: 'أستراليا', image: 'https://picsum.photos/seed/sydop/400/300', description: 'فندق أنيق بإطلالات على ميناء سيدني.' },
  { name: 'هيلتون سيدني', city: 'سيدني', country: 'أستراليا', image: 'https://picsum.photos/seed/hiltsyd/400/300', description: 'فندق مركزي قريب من دار الأوبرا.' },
  { name: 'كراون ميلبورن', city: 'ملبورن', country: 'أستراليا', image: 'https://picsum.photos/seed/crownmel/400/300', description: 'فندق فاخر على ضفاف نهر يارا.' },
  { name: 'أوكلاند هيلتون', city: 'أوكلاند', country: 'نيوزيلندا', image: 'https://picsum.photos/seed/hiltonakl/400/300', description: 'فندق عصري بإطلالات على المرفأ.' },
];

module.exports = { HOTELS };
