const HOTELS = [
  { name: 'فندق شام بالاس', city: 'دمشق', image: 'https://picsum.photos/seed/cham1/400/300', description: 'فندق فاخر يقع في قلب دمشق ويتميز بإطلالات رائعة وخدمة مميزة.' },
  { name: 'فندق الداما روز', city: 'دمشق', image: 'https://picsum.photos/seed/dama1/400/300', description: 'من أعرق فنادق دمشق بتصميم مميز وموقع استراتيجي قرب المطاعم والأسواق.' },
  { name: 'فندق فورسيزونز', city: 'دمشق', image: 'https://picsum.photos/seed/four1/400/300', description: 'فندق عالمي بخدمات راقية ومرافق ترفيهية كاملة وسبا فاخر.' },
  { name: 'فندق شيراتون', city: 'دمشق', image: 'https://picsum.photos/seed/sher1/400/300', description: 'فندق خمس نجوم مع مسبح وصالات اجتماعات وموقع مميز في وسط المدينة.' },
  { name: 'فندق بيت الوالي', city: 'دمشق', image: 'https://picsum.photos/seed/wali1/400/300', description: 'فندق تراثي يعكس روعة العمارة الدمشقية القديمة في البيوت الشامية.' },
  { name: 'فندق البستان', city: 'دمشق', image: 'https://picsum.photos/seed/bust1/400/300', description: 'فندق هادئ يحيط به الحدائق، مثالي للعائلات والاسترخاء.' },
  { name: 'فندق قصر دمشق', city: 'دمشق', image: 'https://picsum.photos/seed/qasr1/400/300', description: 'تجربة إقامة فاخرة بأسلوب الضيافة الدمشقية التقليدية.' },
  { name: 'فندق رامادا', city: 'حلب', image: 'https://picsum.photos/seed/rama1/400/300', description: 'فندق عصري في حلب بغرف مريحة ومطعم متعدد الأصناف.' },
  { name: 'فندق الشرق', city: 'حلب', image: 'https://picsum.photos/seed/shark1/400/300', description: 'من أشهر فنادق حلب التاريخية بالقرب من سوق المدينة القديمة.' },
  { name: 'فندق جبل الشيخ', city: 'اللاذقية', image: 'https://picsum.photos/seed/jabal1/400/300', description: 'إطلالة ساحرة على البحر مع خدمات مريحة لضيوف المدينة الساحلية.' },
  { name: 'فندق الروتانا', city: 'اللاذقية', image: 'https://picsum.photos/seed/rutan1/400/300', description: 'فندق على الشاطئ بمسبح خارجي وغرف عائلية واسعة.' },
  { name: 'فندق المرجان', city: 'طرطوس', image: 'https://picsum.photos/seed/mrjan1/400/300', description: 'وجهة مثالية على ساحل المتوسط بإطلالات بحرية جميلة.' },

  { name: 'فندق برج العرب', city: 'دبي', image: 'https://picsum.photos/seed/burj1/400/300', description: 'أشهر فندق في العالم بتصميم شراع مميز وإطلالات على الخليج العربي.' },
  { name: 'فندق جميرا بيتش', city: 'دبي', image: 'https://picsum.photos/seed/jume1/400/300', description: 'منتججع فاخر على الشاطئ بمرافق مائية رائعة ومطاعم عالمية.' },
  { name: 'فندق أتلانتس النخلة', city: 'دبي', image: 'https://picsum.photos/seed/atla1/400/300', description: 'فندق أسطوري على جزيرة النخلة بأكواريوم ضخم وشاطئ خاص.' },
  { name: 'فندق رافلز دبي', city: 'دبي', image: 'https://picsum.photos/seed/rafl1/400/300', description: 'فخامة استثنائية مع خدمة بوتل خاصة ومطاعم حائزة على نجوم.' },
  { name: 'فندق شيراتون اسطنبول', city: 'إسطنبول', image: 'https://picsum.photos/seed/ista1/400/300', description: 'فندق عصري يطل على مضيق البوسفور مع مسابح ومرافق متكاملة.' },
  { name: 'فندق سيراغان بالاس', city: 'إسطنبول', image: 'https://picsum.photos/seed/cir1/400/300', description: 'قصر عثماني تاريخي تحول إلى فندق فاخر على ضفاف البوسفور.' },
  { name: 'فندق أيا صوفيا مانشنز', city: 'إسطنبول', image: 'https://picsum.photos/seed/ayas1/400/300', description: 'إقامة فاخرة في قلب المدينة القديمة بالقرب من المسجد الأزرق.' },
  { name: 'فندق ماريوت القاهرة', city: 'القاهرة', image: 'https://picsum.photos/seed/cai1/400/300', description: 'فندق مميز في مدينة نصر بغرف واسعة ومطاعم متنوعة.' },
  { name: 'فندق مينا هاوس', city: 'الجيزة', image: 'https://picsum.photos/seed/mena1/400/300', description: 'فندق تاريخي يطل مباشرة على أهرامات الجيزة بتجربة لا تنسى.' },
  { name: 'فندق فورسيزونز القاهرة', city: 'القاهرة', image: 'https://picsum.photos/seed/nile1/400/300', description: 'فندق فاخر على ضفاف النيل بخدمات عالمية ومناظر خلابة.' },
  { name: 'فندق ريتز باريس', city: 'باريس', image: 'https://picsum.photos/seed/paris1/400/300', description: 'فندق أسطوري في قلب باريس يجمع الفخامة والتاريخ العريق.' },
  { name: 'فندق لافينيا أوبيرا', city: 'لندن', image: 'https://picsum.photos/seed/lond1/400/300', description: 'فندق عصري بموقع مميز قرب أوبرا لندن والمعالم السياحية.' },
  { name: 'فندق برج إيفل البلاتيني', city: 'برشلونة', image: 'https://picsum.photos/seed/barc1/400/300', description: 'فندق جميل بجوار شاطئ برشلونة مع تراس بانورامي مميز.' },
  { name: 'فندق رومانتيك روما', city: 'روما', image: 'https://picsum.photos/seed/roma1/400/300', description: 'فندق ساحر قريب من الكولوسيوم بلمسة إيطالية أصيلة.' },
  { name: 'فندق سيام بانكوك', city: 'بانكوك', image: 'https://picsum.photos/seed/bank1/400/300', description: 'منتجع فاخر وسط الطبيعة مع مسابح لا متناهية وخدمة راقية.' },
  { name: 'فندق نيويورك سكاي', city: 'نيويورك', image: 'https://picsum.photos/seed/nyc1/400/300', description: 'فندق حديث في مانهاتن بإطلالات رائعة على المدينة التي لا تنام.' },
  { name: 'فندق الدوحة ويندام', city: 'الدوحة', image: 'https://picsum.photos/seed/doha1/400/300', description: 'فندق أنيق في قلب الدوحة قريب من الكورنيش والأسواق التقليدية.' },
  { name: 'فندق الروافد', city: 'عمان', image: 'https://picsum.photos/seed/amman1/400/300', description: 'فندق مريح في جبل عمان بضيافة أردنية دافئة وإطلالات على المدينة.' },
  { name: 'فندق لافوينت بيروت', city: 'بيروت', image: 'https://picsum.photos/seed/beir1/400/300', description: 'فندق راقٍ على الواجهة البحرية لبيروت بأجواء منعشة.' },
  { name: 'فندق القاهرة الملكي', city: 'المالديف', image: 'https://picsum.photos/seed/mald1/400/300', description: 'منتجع على الماء ببساطة فائقة وشواطئ بكر ومياه فيروزية.' },
  { name: 'فندق طوكيو سكاي تري', city: 'طوكيو', image: 'https://picsum.photos/seed/toky1/400/300', description: 'فندق عصري قريب من برج طوكيو بمشاهد ساحرة للمدينة.' },
  { name: 'فندق المرسى تونس', city: 'تونس', image: 'https://picsum.photos/seed/tunis1/400/300', description: 'فندق بحري أنيق في ضواحي العاصمة التونسية بإطلالة على المتوسط.' },
  { name: 'فندق السرايا مراكش', city: 'مراكش', image: 'https://picsum.photos/seed/mrrak1/400/300', description: 'رياض مغربي تقليدي مفروش بأناقة وسط المدينة العتيقة.' },
  { name: 'فندق البيت المقدس', city: 'القدس', image: 'https://picsum.photos/seed/jeru1/400/300', description: 'فندق هادئ قريب من البلدة القديمة بروحانيات لا توصف.' },
];

module.exports = { HOTELS };
